version: '3'
services:
  ## Postgres database for inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB : ms_inventory
      POSTGRES_USER : unclecode
      POSTGRES_PASSWORD : test123
    ports:
      - 5431:5431
    expose:
      - 5431
    command:
      -p 5431

  ## MySql database for inventory
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: unclecode
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  ## Postgres database for inventory
  db-product:
    container_name: db_products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: unclecode
      POSTGRES_PASSWORD: test123
    ports:
      - 5432:5432
    expose:
      - 5432
    command:
      -p 5432

  ## Postgres database for keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: unclecode
      POSTGRES_PASSWORD: test123
    ports:
      - 5433:5433
    expose:
      - 5433
    command:
      -p 5433

  ## Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      D_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: unclecode
      DB_PASSWORD: test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181